#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# proxy.sh — Caddy reverse proxy with automatic Let's Encrypt certificates.
#
# One Caddy instance serves every installed panel. The Caddyfile is not hand
# edited: it is rendered from the panel state files, so installing or removing a
# panel just re-renders and reloads. That is what makes multiple panels on one
# server work without fighting over ports 80/443.
# ──────────────────────────────────────────────────────────────────────────────

readonly CADDY_CONTAINER="vpnsetup-caddy"

# ──────────────────────────────────────────────────────────────────────────────
# Caddy container
# ──────────────────────────────────────────────────────────────────────────────
proxy_write_compose() {
  mkdir -p "$CADDY_DIR"
  cat > "$CADDY_DIR/docker-compose.yml" <<'YAML'
services:
  caddy:
    image: caddy:2-alpine
    container_name: vpnsetup-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
YAML
}

# _caddy_site_block <domain> <upstream> [allow_ips]
#
# upstream is a literal host:port on this machine (127.0.0.1:2053).
#
# allow_ips is a comma-separated list of IPs/CIDRs. When set, every other client
# gets 403 — except on the ACME challenge path, which must stay reachable or
# certificate renewal breaks the moment the allowlist is enabled.
#
# The allowlist is deliberately NOT applied to subscription sites: clients have
# to be able to fetch their own subscriptions.
_caddy_site_block() {
  local domain="$1" upstream="$2" allow_ips="${3:-}"

  printf '%s {\n' "$domain"
  printf '    encode gzip\n'
  printf '    header {\n'
  printf '        Strict-Transport-Security "max-age=31536000; includeSubDomains"\n'
  printf '        X-Content-Type-Options "nosniff"\n'
  printf '        X-Frame-Options "SAMEORIGIN"\n'
  printf '        Referrer-Policy "no-referrer"\n'
  printf '        -Server\n'
  printf '    }\n'

  if [ -n "$allow_ips" ]; then
    printf '    @denied {\n'
    printf '        not remote_ip %s\n' "$(printf '%s' "$allow_ips" | tr ',' ' ' | tr -s ' ')"
    printf '        not path /.well-known/acme-challenge/*\n'
    printf '    }\n'
    printf '    respond @denied "403 Forbidden" 403\n'
  fi

  printf '    reverse_proxy %s\n' "$upstream"
  printf '}\n\n'
}

# Render the Caddyfile from the site registry.
#
# This iterates sites, not panels. Panels feed the registry (site_sync_from_panel)
# and so does anything else that wants a domain — which is what lets a control
# panel publish itself through the same generator instead of editing this file.
proxy_render() {
  mkdir -p "$CADDY_DIR"
  local tmp="$CADDY_DIR/Caddyfile.tmp.$$"
  local name domain alt upstream allow kind

  {
    printf '# Generated by vpnsetup — do not edit by hand.\n'
    printf '# Sources: %s/*.env — re-render with: vpnsetup proxy\n\n' "$SITES_STATE_DIR"

    local any=0
    while IFS= read -r name; do
      [ -n "$name" ] || continue
      domain="$(site_get "$name" DOMAIN)"
      [ -n "$domain" ] || continue
      upstream="$(site_get "$name" UPSTREAM)"
      [ -n "$upstream" ] || continue
      alt="$(site_get "$name" ALT_DOMAIN)"
      allow="$(site_get "$name" ALLOW_IPS)"
      kind="$(site_get "$name" KIND 'app')"
      any=1

      printf '# %s (%s)\n' "$name" "$kind"
      _caddy_site_block "$domain" "$upstream" "$allow"

      if [ -n "$alt" ] && [ "$alt" != "$domain" ]; then
        printf '# %s — second hostname, same upstream\n' "$name"
        _caddy_site_block "$alt" "$upstream" ""
      fi
    done < <(site_ids)

    if [ "$any" -eq 0 ]; then
      printf '# No sites registered yet.\n'
    fi
  } > "$tmp"

  mv "$tmp" "$CADDY_DIR/Caddyfile"
}

# Warn about anything that would stop Caddy from binding 80/443.
proxy_preflight() {
  local port owner
  for port in 80 443; do
    if port_in_use "$port"; then
      owner="$(docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null | grep -E "0\.0\.0\.0:${port}->|:${port}->" | head -1)"
      if [ -n "$owner" ] && printf '%s' "$owner" | grep -q "^$CADDY_CONTAINER "; then
        continue
      fi
      if [ -n "$owner" ]; then
        log_warn "Port $port is already bound by container: $owner"
      else
        log_warn "Port $port is already in use on this host."
      fi
      log_warn "Caddy needs ports 80 and 443 free to issue certificates."
      if ! confirm "Continue anyway?" "n"; then return 1; fi
    fi
  done
  return 0
}

# proxy_up — ensure the container runs and the config is applied.
proxy_up() {
  ensure_docker
  proxy_write_compose
  proxy_render

  if container_running "$CADDY_CONTAINER"; then
    proxy_reload || return 1
    return 0
  fi

  proxy_preflight || return 1

  log_info "Starting Caddy..."
  dc "$CADDY_DIR" up -d || die "Could not start Caddy."

  if wait_container_running "$CADDY_CONTAINER" 60; then
    log_ok "Caddy is running — certificates are issued automatically."
    return 0
  fi
  log_error "Caddy did not start. Logs:"
  docker logs --tail=40 "$CADDY_CONTAINER" 2>&1 | sed 's/^/    /' >&2 || true
  return 1
}

# proxy_reload — apply a re-rendered Caddyfile without dropping connections.
proxy_reload() {
  proxy_render
  if ! container_running "$CADDY_CONTAINER"; then
    return 1
  fi

  # Validate before swapping the live config in. A generated file with a syntax
  # error should be reported, not applied — and a failed reload must not take
  # down a proxy that is currently serving traffic.
  if ! docker exec "$CADDY_CONTAINER" caddy validate \
         --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
    log_error "The generated Caddyfile is invalid — keeping the running config."
    docker exec "$CADDY_CONTAINER" caddy validate \
      --config /etc/caddy/Caddyfile --adapter caddyfile 2>&1 | tail -5 | sed 's/^/    /' >&2 || true
    return 1
  fi

  if docker exec "$CADDY_CONTAINER" caddy reload \
       --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
    log_ok "Caddy config reloaded"
    return 0
  fi

  log_warn "Hot reload failed — restarting Caddy."
  dc "$CADDY_DIR" restart >/dev/null 2>&1 || true
  return 0
}

# proxy_wait_for_cert <domain> <timeout> — poll until TLS is actually serving.
proxy_wait_for_cert() {
  local domain="$1" timeout="${2:-90}" waited=0
  log_info "Waiting for a TLS certificate for $domain (Let's Encrypt)..."
  while [ "$waited" -lt "$timeout" ]; do
    if curl -fsS -o /dev/null --max-time 8 "https://$domain" 2>/dev/null; then
      log_ok "https://$domain is live"
      return 0
    fi
    sleep 5
    waited=$((waited + 5))
  done
  log_warn "Certificate not confirmed within ${timeout}s."
  log_warn "Check that the DNS A-record for $domain points here and that ports 80/443 are open."
  log_dim "  docker logs $CADDY_CONTAINER"
  return 1
}

proxy_status() {
  printf '\n%sCaddy:%s %s\n' "$C_BOLD" "$C_RESET" "$(container_state "$CADDY_CONTAINER")"
  if [ -f "$CADDY_DIR/Caddyfile" ]; then
    printf '%sSites:%s\n' "$C_BOLD" "$C_RESET"
    grep -E '^[^#[:space:]].*\{$' "$CADDY_DIR/Caddyfile" 2>/dev/null | sed 's/[[:space:]]*{$//' | sed 's/^/  /' || true
  fi
}

proxy_remove() {
  compose_down "$CADDY_DIR" purge
  rm -rf "$CADDY_DIR"
}
