#!/usr/bin/env bash
# Installs the vpnsetup web control panel on the same host as the panels:
#   - copies web/ to /opt/vpnsetup-web, builds the frontend, writes /etc/vpnsetup-web.env
#   - runs it as vpnweb:vpnsetup under systemd (socket access via the vpnsetup group)
#   - publishes it through Caddy with `vpnsetup site add web`
#
# Usage:
#   sudo bash web/deploy/install.sh [--domain panel.example.com]
#   WEB_DOMAIN=... WEB_ADMIN_USER=... WEB_ADMIN_PASSWORD=... sudo -E bash web/deploy/install.sh
set -uo pipefail

APP_DIR="/opt/vpnsetup-web"
ENV_FILE="/etc/vpnsetup-web.env"
UNIT_SRC=""
UNIT_DST="/etc/systemd/system/vpnsetup-web.service"
SERVICE_USER="vpnweb"
SERVICE_GROUP="vpnsetup"
WEB_PORT="${WEB_PORT:-3100}"

C_RED=''; C_GREEN=''; C_YELLOW=''; C_CYAN=''; C_RESET=''
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  C_RED=$'\033[0;31m'; C_GREEN=$'\033[0;32m'; C_YELLOW=$'\033[0;33m'
  C_CYAN=$'\033[0;36m'; C_RESET=$'\033[0m'
fi
say()  { printf '%s[INFO]%s %s\n' "$C_CYAN" "$C_RESET" "$*"; }
ok()   { printf '%s[ OK ]%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%s[WARN]%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
fail() { printf '%s[FAIL]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "Run as root: sudo bash web/deploy/install.sh"

# Locate the repo checkout: this script lives in web/deploy/.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
[ -f "$REPO/web/package.json" ] || fail "Cannot find web/package.json under $REPO"
UNIT_SRC="$REPO/web/deploy/vpnsetup-web.service"

DOMAIN="${WEB_DOMAIN:-}"
while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --domain=*) DOMAIN="${1#*=}"; shift ;;
    *) shift ;;
  esac
done
if [ -z "$DOMAIN" ] && [ -t 0 ]; then
  read -rp "Panel domain (e.g. panel.example.com): " DOMAIN || DOMAIN=""
fi
[ -n "$DOMAIN" ] || fail "Domain required: --domain or WEB_DOMAIN"

ADMIN_USER="${WEB_ADMIN_USER:-admin}"
ADMIN_PASS="${WEB_ADMIN_PASSWORD:-}"
if [ -z "$ADMIN_PASS" ]; then
  [ -t 0 ] || fail "No terminal: set WEB_ADMIN_PASSWORD"
  read -rsp "Admin password for $ADMIN_USER: " ADMIN_PASS || ADMIN_PASS=""
  printf '\n'
fi
[ -n "$ADMIN_PASS" ] || fail "Empty password refused"

command -v bun >/dev/null 2>&1 || {
  say "Installing Bun..."
  BUN_INSTALL=/usr/local bash -c "$(curl -fsSL https://bun.sh/install)" \
    || fail "Bun installation failed"
}
[ -x /usr/local/bin/bun ] || fail "bun not found at /usr/local/bin/bun"
ok "Bun: $(bun --version)"

getent group "$SERVICE_GROUP" >/dev/null 2>&1 || groupadd --system "$SERVICE_GROUP"
id "$SERVICE_USER" >/dev/null 2>&1 \
  || useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
usermod -aG "$SERVICE_GROUP" "$SERVICE_USER"
ok "User $SERVICE_USER in group $SERVICE_GROUP"

say "Copying web/ to $APP_DIR..."
mkdir -p "$APP_DIR"
tar --exclude='node_modules' --exclude='dist' --exclude='.env' \
  -cf - -C "$REPO/web" . | tar -xf - -C "$APP_DIR"
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$APP_DIR"

say "Installing dependencies + building frontend..."
sudo -u "$SERVICE_USER" bun install --cwd "$APP_DIR" \
  || fail "bun install failed"
sudo -u "$SERVICE_USER" bun run --cwd "$APP_DIR" build \
  || fail "frontend build failed"
ok "Frontend built"

say "Writing $ENV_FILE..."
HASH="$(sudo -u "$SERVICE_USER" bun "$APP_DIR/server/hash-password.ts" "$ADMIN_PASS")"
[ -n "$HASH" ] || fail "Could not hash the password"
umask 027
cat > "$ENV_FILE" <<EOF
# Generated by web/deploy/install.sh — do not commit.
WEB_PORT=$WEB_PORT
WEB_ADMIN_USER=$ADMIN_USER
WEB_ADMIN_PASSWORD_HASH=$HASH
VPN_SETUP_AGENT_SOCKET=/run/vpnsetup/agent.sock
# Optional: fill in the panels you manage.
#MARZBAN_URL=http://127.0.0.1:8000
#MARZBAN_USERNAME=
#MARZBAN_PASSWORD=
#REMNAWAVE_URL=http://127.0.0.1:3000
#REMNAWAVE_TOKEN=
#XUI_URL=http://127.0.0.1:2053
#XUI_TOKEN=
EOF
chown "root:$SERVICE_GROUP" "$ENV_FILE"
chmod 640 "$ENV_FILE"
ok "Env written (panel credentials are commented out — edit $ENV_FILE)"

cp "$UNIT_SRC" "$UNIT_DST"
systemctl daemon-reload
systemctl enable --now vpnsetup-web \
  || fail "Could not start vpnsetup-web (journalctl -u vpnsetup-web)"
sleep 2
systemctl is-active --quiet vpnsetup-web \
  || fail "vpnsetup-web is not running (journalctl -u vpnsetup-web)"
ok "vpnsetup-web is running on 127.0.0.1:$WEB_PORT"

if command -v vpnsetup >/dev/null 2>&1; then
  say "Publishing through Caddy..."
  vpnsetup site add web --domain "$DOMAIN" --upstream "127.0.0.1:$WEB_PORT" \
    && ok "Panel: https://$DOMAIN" \
    || warn "site add failed — run manually: vpnsetup site add web --domain $DOMAIN --upstream 127.0.0.1:$WEB_PORT"
else
  warn "vpnsetup not found — publish manually behind your proxy to 127.0.0.1:$WEB_PORT"
fi

printf '\n%sDone.%s Login: %s\n' "$C_GREEN" "$C_RESET" "$ADMIN_USER"
printf 'Logs: journalctl -u vpnsetup-web -f\n'
printf 'Panel credentials: %s (then: systemctl restart vpnsetup-web)\n' "$ENV_FILE"
